spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sms
    username: postgres
    password: Rajeev@2345

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  secret_key: RAJEEV@@#$%
